Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/ming/Documents/TieComm/main.py", line 175, in <module>
    main(args)
  File "/Users/ming/Documents/TieComm/main.py", line 113, in main
    log = runner.train_batch(epoch_size)
  File "/Users/ming/Documents/TieComm/runner/runner.py", line 38, in train_batch
    train_log = self.compute_grad(batch_data)
  File "/Users/ming/Documents/TieComm/runner/runner.py", line 137, in compute_grad
    coop_returns[i] = rewards[i] + self.args.gamma * prev_coop_return * (1-episode_masks[i])
RuntimeError: The expanded size of the tensor (1) must match the existing size (10) at non-singleton dimension 0.  Target sizes: [1].  Tensor sizes: [10]