Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/ming/Documents/TieComm/main.py", line 171, in <module>
    main(args)
  File "/Users/ming/Documents/TieComm/main.py", line 109, in main
    log = runner.train_batch(epoch_size)
  File "/Users/ming/Documents/TieComm/runner/runner.py", line 36, in train_batch
    batch_data, batch_log = self.collect_epoch_data(epoch_size)
  File "/Users/ming/Documents/TieComm/runner/runner.py", line 55, in collect_epoch_data
    episode_data, episode_log = self.run_an_episode()
  File "/Users/ming/Documents/TieComm/runner/runner.py", line 74, in run_an_episode
    obs = self.env.get_obs()
  File "/Users/ming/Documents/TieComm/envs/traffic_junction/env_wrappers.py", line 110, in get_obs
    obs = self.env._get_obs()
  File "/opt/anaconda3/envs/tiecomm/lib/python3.8/site-packages/gym/core.py", line 235, in __getattr__
    raise AttributeError(
AttributeError: attempted to get missing private attribute '_get_obs'