
<module 'envs.mpe.large_spread_v1' from '/Users/ming/Documents/TieComm/envs/mpe/large_spread_v1.py'>
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/ming/Documents/TieComm/main.py", line 176, in <module>
    main(args)
  File "/Users/ming/Documents/TieComm/main.py", line 114, in main
    log = runner.train_batch(epoch_size)
  File "/Users/ming/Documents/TieComm/modules/multi_processing.py", line 82, in train_batch
    batch_data, batch_log = self.runner.collect_epoch_data(epoch_size)
  File "/Users/ming/Documents/TieComm/runner/runner.py", line 52, in collect_epoch_data
    episode_data, episode_log = self.run_an_episode()
  File "/Users/ming/Documents/TieComm/runner/runner.py", line 82, in run_an_episode
    next_obs, rewards, done, env_info = self.env.step(actions)
ValueError: not enough values to unpack (expected 4, got 3)